### ISSUE TITLE
Can't override email template as Django returns original as first match

### ISSUE THREAD

**Issue by riklaunim** [macropin/django-registration#50]
After upgrading from old django-registration to redux version my email template rendering blow up. 

When I use django:
   loader.select_template(['registration/activation_email.txt'])
I get the django-registration original template (while my overriden template is in my_app/templates/registration/activation_email.txt). The my_app/templates is discovered by AppDirectory template loader, it's on the django.template.loaders.app_directories.app_template_dirs folders list, but after "registration" app templates folder (as it's after "registration" on the INSTALLED_APPS lists).

select_template calls get_template which returns first match. For some reason it worked before, but now (Django 1.7.7 and @master django-registration-redux) it does not. I can hack it by providing dirs value (either filtered or reversed):

        from django.template.loaders.app_directories import app_template_dirs
        dirs = sorted(app_template_dirs, reverse=True)
        template = loader.select_template(['registration/activation_email.txt'], dirs=dirs)

But it would be good to know why and what is going on. It should "just work".

**Comment by AMeng** [comment]
I'm able to reproduce this. Appears to have been introduced in https://github.com/macropin/django-registration/commit/12aba225843023cc7355406e7c984eec733f4a2d when templates were added to the application. Django version should not matter here.

**To reproduce this:** Override `registration/activation_email.txt` but do *not* override `registration/activation_email.html`. The default `.html` template will be used in the emails.

**Cause:** The issue is that the code first looks for the `.txt` version of the template, and then checks for the `.html` version. It finds your `.txt` version just fine, but then finds the newly included `.html` template, and uses that instead.

Before https://github.com/macropin/django-registration/commit/12aba225843023cc7355406e7c984eec733f4a2d, no templates were included, so if you never created a `.html` version, your `.txt` version would be used.

**Comment by AMeng** [comment]
@riklaunim this was addressed in https://github.com/macropin/django-registration/pull/57.

The solution is to either override the `registration/activation_email.html` template or add the following to settings.py:

```python
REGISTRATION_EMAIL_HTML = False
```

**Comment by riklaunim** [comment]
I'll check this out.

**Comment by riklaunim** [comment]
I have both .txt and .html templates

**Comment by riklaunim** [comment]
This doesn't solve the problem. I've override both templates and more and still the .txt template is fetched in the original form (/env/lib/python3.4/site-packages/registration/templates/registration/activation_email.txt) which results in

```django.core.urlresolvers.NoReverseMatch: Reverse for 'registration_activate' with arguments '('',)' and keyword arguments '{}' not found. 0 pattern(s) tried: []```

**Comment by michela** [comment]
Able to repro error with Django 1.8.1/django-registration-redux==1.2c0/python2.7

 riklaunim can you elaborate on your hack above so I can try it? 

>  I can hack it by providing dirs value (either filtered or reversed):

Is this a patch to django-registration-redux?

**Comment by michela** [comment]
Ugly workaround for anyone else with broken password reset:

Move the django.contrib.admin.template out of the way so app templates used

./site-packages/django/contrib/admin/templates/registration$ mv password_reset_email.html password_reset_email.html.ori

Advice on cleaner approach pre-patch welcome!

**Comment by riklaunim** [comment]
For django 1.7 you can pass a list of directories for the select_template and other methods:

```
from django.template.loaders.app_directories import app_template_dirs
dirs = sorted(app_template_dirs, reverse=True)

template = loader.select_template(MY_TEMPLATES_NAMES_HERE, dirs=dirs)
```
When it's reversed it finds my template first and uses it. For Django 1.8 the API is totally different and I don't know if there is an equivalent hack for this. It should work without hacks in the first place.

**Comment by AMeng** [comment]
I'm not able to reproduce the broken overrides. Can you post your settings.py? I'm curious about your `INSTALLED_APPS`, `TEMPLATE_DIRS`, and `TEMPLATE_LOADERS` settings. I'm also curious if you've seen this same issue with any other third party Django apps?

**Comment by riklaunim** [comment]
In INSTALLED_APPS registration is before my app. I have app_directories and filesystem loaders and reversing their order doesn't help either. Seems like other third party templates get overriden as before. TEMPLATES_DIR is not used.

**Comment by michela** [comment]
AMeng, I haven't seen this issue with any other apps. Stripped out legacy loaders that aren't used in Django 1.8 startproject script

TEMPLATE_LOADERS = (
	'django.template.loaders.app_directories.Loader',
)
TEMPLATE_DIRS = (os.path.join(BASE_DIR, "templates"),)
INSTALLED_APPS = (
	'django.contrib.staticfiles',
	'django_extensions',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    # Uncomment the next line to enable the admin:
    'django.contrib.admin',
    # Uncomment the next line to enable admin documentation:
    'django.contrib.admindocs',
	'django_granular_permissions',
	'prod',
    'registration',
	'rest_framework',
    'debug_toolbar',
#	'django_mobile',
	'django_nose',
	'paypal.standard.ipn',
	'django_jenkins',
	'floppyforms',
)

**Comment by riklaunim** [comment]
It's possible that an odd import of itself within django-registration causes Django to register the application or its templates to soon.

**Comment by riklaunim** [comment]
https://docs.djangoproject.com/en/1.7/ref/templates/api/#django.template.loaders.app_directories.Loader INSTALLED_APPS order causes this.

The solution is to use TEMPLATE_DIRS:
```
BASE_DIR = os.path.dirname(os.path.dirname(__file__))
TEMPLATE_DIRS = (
    os.path.join(BASE_DIR, 'your_app/templates/'),
)
```

Or put templates in an application that can go before "registration" in INSTALLED_APPs (my app has some import/model dependencies so I would have to move the templates to blank new app).

**Comment by AMeng** [comment]
Sounds like this is just a side effect of including templates in a third party application. I don't think there is anything we can do within the project to improve this experience.

**Comment by slogan621** [comment]
For me this was caused by the following in settings.py:

TEMPLATE_DIRS = (
    os.path.join(SITE_ROOT, 'templates'),
    os.path.join(SITE_ROOT, 'templates/registration'),
)

Commenting out the second line fixed it. I was doing an upgrade from django 1.3 to 1.8 when I encountered the issue.

**Comment by clee842** [comment]
@michela Hello, I tried something similar to what you said and then the email template overriding now works properly.

I moved 'django.contrib.admin' **below** 'registration' in my INSTALLED_APPS.

The admin app was having priority with template rendering over other apps.

Thank you.
